EnableLogging: true
KickMessage: "[player] is kicked by KerisuteGomen\nBlocked Mods: [mods]"
KickMessageReceiver: []
Forge:
  CanLogin: true
  ModCheck: true
  EnableModIDWhitelist: true
  Whitelist: []
LiteLoader:
  CanLogin: true
  ModCheck: true
  EnableModIDWhitelist: true
  Whitelist: []
NonForge5zig:
  CanLogin: true
LabyMod:
  CanLogin: true
RegisterCustomClients: []
OtherClient:
  CanLogin: false

Logging:
KickMessage: "[player] is kicked by KerisuteGomen\nBlocked Mods: [mods]"
Forge:
  Login: true
  ModsCheck: true
  UseWhitelist: true
  Whitelist: []
LiteLoader:
  Login: true
  ModsCheck: true
  UseWhitelist: true
  Whitelist: []
NonForge5zig:
  Login: true
LabyMod:
  Login: true
OtherClients:
  Login: true
  ClientsCheck: true
  UseWhitelist: true
  Whitelist: []